name: pipeline CI/CD Frontend-api



env:
    IMAGE_NAME: frontend-s8-image
    BUILD_NUMBER: ${{github.run_number}}
    VITE_API_URL: https://api.41.lebondeveloppeur.net
on:
    push:
        branches:
            - main

jobs:
    test-job:
  
        runs-on: ubuntu-latest
             
        steps:
        - name: Clone Source Code
          uses: actions/checkout@v4
        
        - name: Set up Node js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        
        - name: install dependencies
          run: npm install --force

        - name: Run unit Tests
          run: npm test
    
    build-and-push-job:
        runs-on: ubuntu-latest
        needs: test-job 
        steps:
            - name: Clone Source Code
              uses: actions/checkout@v4 

            - name: Build Docker image
              run: docker build -t ${{ env.IMAGE_NAME }} --build-arg VITE_API_URL=${{ env.VITE_API_URL }}  .

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{  secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Tag Docker image with specific version
              run: docker tag ${{ env.IMAGE_NAME }}  ${{  secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
            

            - name: Push Docker image with specific version
              run: docker push ${{  secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }} 

            - name: Tag Docker image with latest version
              run: docker tag ${{ env.IMAGE_NAME }}  ${{  secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

            - name: Push Docker image with latest version
              run: docker push ${{  secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest 


    






